### ISSUE TITLE
Just quick question on efficiency

### ISSUE THREAD

**Issue by hohoCode** [kemaswill/fasttext_torch#1]
Thanks for the great opensource! Just one quick question on its efficiency:  Have you compared the speed performance of your codes with FB's implementation? In general what is the speed difference, like ~10% or ~30% (or more) speed difference?

Thanks!

**Comment by junwei-pan** [comment]
The FB's implementation is probably significantly faster than this one. I have compared the FB's complementation and my [keras implementation of fasttext](https://github.com/fchollet/keras/blob/master/examples/imdb_fasttext.py), and FB is 5 times faster than it. Please refer to this [pull request](https://github.com/fchollet/keras/pull/3446) for more details.

**Comment by hohoCode** [comment]
Nice work! Thanks for sharing.
